import '../../domain/models/dsa_problem.dart';

class StriverA2ZData {
  static List<DsaProblem> getInitialProblems() {
    return [
      // Step 1: Learn the Basics
      const DsaProblem(
        id: 's1-1',
        stepNumber: 1,
        stepTitle: 'Step 1: Learn the Basics',
        subTopic: '1.1 Things to Know in C++/Java/Python',
        title: 'User Input / Output, Data Types, If-Else, Switch',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Syntax & Language Basics',
        problemUrl: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
        timeSpentMinutes: 30,
      ),
      const DsaProblem(
        id: 's1-2',
        stepNumber: 1,
        stepTitle: 'Step 1: Learn the Basics',
        subTopic: '1.2 Build-up Logical Thinking',
        title: 'Pattern Printing (Patterns 1 to 22)',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Nested Loops',
        problemUrl: 'https://takeuforward.org/patterns/pattern-1-rectangular-star-pattern/',
        timeSpentMinutes: 45,
      ),
      const DsaProblem(
        id: 's1-3',
        stepNumber: 1,
        stepTitle: 'Step 1: Learn the Basics',
        subTopic: '1.4 Know Basic Maths',
        title: 'Count Digits, Reverse a Number, Check Palindrome, GCD/HCF',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Basic Mathematical Logic',
        problemUrl: 'https://leetcode.com/problems/reverse-integer/',
        timeSpentMinutes: 25,
      ),
      const DsaProblem(
        id: 's1-4',
        stepNumber: 1,
        stepTitle: 'Step 1: Learn the Basics',
        subTopic: '1.5 Learn Basic Recursion',
        title: 'Print 1 to N, Sum of first N numbers, Reverse an Array, String Palindrome',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Base Case & Recursive Step',
        problemUrl: 'https://leetcode.com/problems/valid-palindrome/',
        timeSpentMinutes: 40,
      ),
      const DsaProblem(
        id: 's1-5',
        stepNumber: 1,
        stepTitle: 'Step 1: Learn the Basics',
        subTopic: '1.6 Learn Basic Hashing',
        title: 'Count Frequency of elements, Highest/Lowest Frequency Element',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Hash Maps & Frequency Arrays',
        problemUrl: 'https://leetcode.com/problems/frequency-of-the-most-frequent-element/',
        timeSpentMinutes: 35,
      ),

      // Step 2: Sorting Techniques
      const DsaProblem(
        id: 's2-1',
        stepNumber: 2,
        stepTitle: 'Step 2: Learn Important Sorting Techniques',
        subTopic: '2.1 Sorting-I',
        title: 'Selection Sort, Bubble Sort, Insertion Sort',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'In-Place Comparison Sorting',
        problemUrl: 'https://takeuforward.org/sorting/selection-sort-algorithm/',
        timeSpentMinutes: 50,
      ),
      const DsaProblem(
        id: 's2-2',
        stepNumber: 2,
        stepTitle: 'Step 2: Learn Important Sorting Techniques',
        subTopic: '2.2 Sorting-II',
        title: 'Merge Sort (Divide and Conquer)',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.solved,
        pattern: 'Divide & Conquer',
        problemUrl: 'https://leetcode.com/problems/sort-an-array/',
        timeSpentMinutes: 60,
      ),
      const DsaProblem(
        id: 's2-3',
        stepNumber: 2,
        stepTitle: 'Step 2: Learn Important Sorting Techniques',
        subTopic: '2.2 Sorting-II',
        title: 'Quick Sort (Partitioning & Pivot)',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.inProgress,
        pattern: 'Pivot Partitioning',
        problemUrl: 'https://takeuforward.org/data-structure/quick-sort-algorithm/',
        timeSpentMinutes: 45,
      ),

      // Step 3: Solve Problems on Arrays
      const DsaProblem(
        id: 's3-1',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.1 Easy Array Problems',
        title: 'Second Largest Element in an Array without sorting',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Single Pass Traversal',
        problemUrl: 'https://www.geeksforgeeks.org/problems/second-largest3735/1',
        timeSpentMinutes: 20,
      ),
      const DsaProblem(
        id: 's3-2',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.1 Easy Array Problems',
        title: 'Remove Duplicates in-place from Sorted Array',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Two Pointers (Slow & Fast)',
        problemUrl: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/',
        timeSpentMinutes: 15,
      ),
      const DsaProblem(
        id: 's3-3',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.1 Easy Array Problems',
        title: 'Left Rotate an Array by D places',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Reversal Algorithm',
        problemUrl: 'https://leetcode.com/problems/rotate-array/',
        timeSpentMinutes: 25,
      ),
      const DsaProblem(
        id: 's3-4',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.1 Easy Array Problems',
        title: 'Move Zeroes to End',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Two Pointers Partition',
        problemUrl: 'https://leetcode.com/problems/move-zeroes/',
        timeSpentMinutes: 15,
      ),
      const DsaProblem(
        id: 's3-5',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.1 Easy Array Problems',
        title: 'Find the Union and Intersection of two sorted arrays',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Two Pointers on Two Arrays',
        problemUrl: 'https://leetcode.com/problems/intersection-of-two-arrays/',
        timeSpentMinutes: 30,
      ),
      const DsaProblem(
        id: 's3-6',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.1 Easy Array Problems',
        title: 'Find missing number in an array',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'XOR / Mathematical Sum',
        problemUrl: 'https://leetcode.com/problems/missing-number/',
        timeSpentMinutes: 15,
      ),
      const DsaProblem(
        id: 's3-7',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.1 Easy Array Problems',
        title: 'Maximum Consecutive Ones',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Single Pass Counter',
        problemUrl: 'https://leetcode.com/problems/max-consecutive-ones/',
        timeSpentMinutes: 10,
      ),
      const DsaProblem(
        id: 's3-8',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Two Sum (Check if pair with given sum exists)',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.solved,
        pattern: 'Hash Map Lookup / Two Pointers',
        problemUrl: 'https://leetcode.com/problems/two-sum/',
        timeSpentMinutes: 20,
      ),
      const DsaProblem(
        id: 's3-9',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Sort an array of 0s, 1s and 2s (Dutch National Flag)',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.solved,
        pattern: '3-Way Partitioning',
        problemUrl: 'https://leetcode.com/problems/sort-colors/',
        timeSpentMinutes: 25,
      ),
      const DsaProblem(
        id: 's3-10',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Majority Element (> N/2 times) (Moore Voting Algorithm)',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.solved,
        pattern: 'Boyer-Moore Voting',
        problemUrl: 'https://leetcode.com/problems/majority-element/',
        timeSpentMinutes: 25,
      ),
      const DsaProblem(
        id: 's3-11',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Kadane Algorithm (Maximum Subarray Sum)',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.solved,
        pattern: 'Dynamic Kadane Accumulation',
        problemUrl: 'https://leetcode.com/problems/maximum-subarray/',
        timeSpentMinutes: 30,
      ),
      const DsaProblem(
        id: 's3-12',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Stock Buy and Sell (Max Profit with single transaction)',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Running Minimum Tracking',
        problemUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
        timeSpentMinutes: 15,
      ),
      const DsaProblem(
        id: 's3-13',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Rearrange Array Elements by Sign',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.solved,
        pattern: 'Two Pointers Alternating',
        problemUrl: 'https://leetcode.com/problems/rearrange-array-elements-by-sign/',
        timeSpentMinutes: 20,
      ),
      const DsaProblem(
        id: 's3-14',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Next Permutation',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.inProgress,
        pattern: 'Lexicographical Peak & Swap',
        problemUrl: 'https://leetcode.com/problems/next-permutation/',
        timeSpentMinutes: 45,
      ),
      const DsaProblem(
        id: 's3-15',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Leaders in an Array (Elements greater than all right elements)',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Reverse Traversal with Max',
        problemUrl: 'https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1',
        timeSpentMinutes: 15,
      ),
      const DsaProblem(
        id: 's3-16',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Longest Consecutive Sequence in an Array',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Hash Set Sequence Expansion',
        problemUrl: 'https://leetcode.com/problems/longest-consecutive-sequence/',
      ),
      const DsaProblem(
        id: 's3-17',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Set Matrix Zeroes',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'In-Place Matrix State Markers',
        problemUrl: 'https://leetcode.com/problems/set-matrix-zeroes/',
      ),
      const DsaProblem(
        id: 's3-18',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Rotate Matrix by 90 Degrees Clockwise',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Transpose and Reverse',
        problemUrl: 'https://leetcode.com/problems/rotate-image/',
      ),
      const DsaProblem(
        id: 's3-19',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.2 Medium Array Problems',
        title: 'Print the Matrix in Spiral Manner',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Boundary Pointer Shrink',
        problemUrl: 'https://leetcode.com/problems/spiral-matrix/',
      ),
      const DsaProblem(
        id: 's3-20',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.3 Hard Array Problems',
        title: 'Pascal Triangle (All 3 Variations)',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Combinatorics & Row Formula',
        problemUrl: 'https://leetcode.com/problems/pascals-triangle/',
      ),
      const DsaProblem(
        id: 's3-21',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.3 Hard Array Problems',
        title: 'Majority Element (> N/3 times)',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Extended Boyer-Moore (2 Candidates)',
        problemUrl: 'https://leetcode.com/problems/majority-element-ii/',
      ),
      const DsaProblem(
        id: 's3-22',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.3 Hard Array Problems',
        title: '3-Sum Problem',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Sort + Two Pointers',
        problemUrl: 'https://leetcode.com/problems/3sum/',
      ),
      const DsaProblem(
        id: 's3-23',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.3 Hard Array Problems',
        title: '4-Sum Problem',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Nested Loops + Two Pointers',
        problemUrl: 'https://leetcode.com/problems/4sum/',
      ),
      const DsaProblem(
        id: 's3-24',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.3 Hard Array Problems',
        title: 'Merge Overlapping Sub-intervals',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Sort by Start Time + Linear Merge',
        problemUrl: 'https://leetcode.com/problems/merge-intervals/',
      ),
      const DsaProblem(
        id: 's3-25',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.3 Hard Array Problems',
        title: 'Merge Two Sorted Arrays Without Extra Space (Gap Method)',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Gap Method / Shell Sort Intuition',
        problemUrl: 'https://leetcode.com/problems/merge-sorted-array/',
      ),
      const DsaProblem(
        id: 's3-26',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.3 Hard Array Problems',
        title: 'Count Inversions in an Array',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Merge Sort Inversion Counting',
        problemUrl: 'https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1',
      ),
      const DsaProblem(
        id: 's3-27',
        stepNumber: 3,
        stepTitle: 'Step 3: Solve Problems on Arrays',
        subTopic: '3.3 Hard Array Problems',
        title: 'Reverse Pairs (LeetCode 493)',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Modified Merge Sort',
        problemUrl: 'https://leetcode.com/problems/reverse-pairs/',
      ),

      // Step 4: Binary Search
      const DsaProblem(
        id: 's4-1',
        stepNumber: 4,
        stepTitle: 'Step 4: Binary Search [1D, 2D, Search Space]',
        subTopic: '4.1 BS on 1D Arrays',
        title: 'Binary Search to find X in sorted array (Iterative & Recursive)',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.solved,
        pattern: 'Standard Low/High Halving',
        problemUrl: 'https://leetcode.com/problems/binary-search/',
        timeSpentMinutes: 15,
      ),
      const DsaProblem(
        id: 's4-2',
        stepNumber: 4,
        stepTitle: 'Step 4: Binary Search [1D, 2D, Search Space]',
        subTopic: '4.1 BS on 1D Arrays',
        title: 'Implement Lower Bound and Upper Bound',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.solved,
        pattern: 'Binary Search Boundary Determination',
        problemUrl: 'https://takeuforward.org/arrays/implement-lower-bound-bs-2/',
        timeSpentMinutes: 20,
      ),
      const DsaProblem(
        id: 's4-3',
        stepNumber: 4,
        stepTitle: 'Step 4: Binary Search [1D, 2D, Search Space]',
        subTopic: '4.1 BS on 1D Arrays',
        title: 'Search in Rotated Sorted Array I & II',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Sorted Half Identification',
        problemUrl: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
      ),
      const DsaProblem(
        id: 's4-4',
        stepNumber: 4,
        stepTitle: 'Step 4: Binary Search [1D, 2D, Search Space]',
        subTopic: '4.2 BS on Answers / Search Space',
        title: 'Find square root of a number in log n',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.todo,
        pattern: 'Monotonic Search Space BS',
        problemUrl: 'https://leetcode.com/problems/sqrtx/',
      ),
      const DsaProblem(
        id: 's4-5',
        stepNumber: 4,
        stepTitle: 'Step 4: Binary Search [1D, 2D, Search Space]',
        subTopic: '4.2 BS on Answers / Search Space',
        title: 'Koko Eating Bananas (LeetCode 875)',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Min-Max Feasibility BS',
        problemUrl: 'https://leetcode.com/problems/koko-eating-bananas/',
      ),
      const DsaProblem(
        id: 's4-6',
        stepNumber: 4,
        stepTitle: 'Step 4: Binary Search [1D, 2D, Search Space]',
        subTopic: '4.2 BS on Answers / Search Space',
        title: 'Book Allocation Problem / Aggressive Cows',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Predicate Function Optimization',
        problemUrl: 'https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1',
      ),

      // Step 6: LinkedList
      const DsaProblem(
        id: 's6-1',
        stepNumber: 6,
        stepTitle: 'Step 6: Learn LinkedList [Single, Double, Medium, Hard]',
        subTopic: '6.1 Learn 1D LinkedList',
        title: 'Introduction to LinkedList, Array to LL, Insert/Delete Node',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.todo,
        pattern: 'Node Pointer Manipulation',
        problemUrl: 'https://leetcode.com/problems/design-linked-list/',
      ),
      const DsaProblem(
        id: 's6-2',
        stepNumber: 6,
        stepTitle: 'Step 6: Learn LinkedList [Single, Double, Medium, Hard]',
        subTopic: '6.3 Medium Problems of LL',
        title: 'Reverse a LinkedList [Iterative and Recursive]',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.todo,
        pattern: '3-Pointer Inversion',
        problemUrl: 'https://leetcode.com/problems/reverse-linked-list/',
      ),
      const DsaProblem(
        id: 's6-3',
        stepNumber: 6,
        stepTitle: 'Step 6: Learn LinkedList [Single, Double, Medium, Hard]',
        subTopic: '6.3 Medium Problems of LL',
        title: 'Detect a Cycle in LL & Find Starting Point of Loop',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Floyd Tortoise and Hare',
        problemUrl: 'https://leetcode.com/problems/linked-list-cycle-ii/',
      ),
      const DsaProblem(
        id: 's6-4',
        stepNumber: 6,
        stepTitle: 'Step 6: Learn LinkedList [Single, Double, Medium, Hard]',
        subTopic: '6.3 Medium Problems of LL',
        title: 'Find Middle of LL (Tortoise-Hare Method)',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.todo,
        pattern: 'Fast and Slow Pointer',
        problemUrl: 'https://leetcode.com/problems/middle-of-the-linked-list/',
      ),
      const DsaProblem(
        id: 's6-5',
        stepNumber: 6,
        stepTitle: 'Step 6: Learn LinkedList [Single, Double, Medium, Hard]',
        subTopic: '6.3 Medium Problems of LL',
        title: 'Delete Nth node from the back of the LL',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Offset Two Pointers',
        problemUrl: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/',
      ),
      const DsaProblem(
        id: 's6-6',
        stepNumber: 6,
        stepTitle: 'Step 6: Learn LinkedList [Single, Double, Medium, Hard]',
        subTopic: '6.3 Medium Problems of LL',
        title: 'Add 2 numbers represented as Linked Lists',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Simultaneous Traversal with Carry',
        problemUrl: 'https://leetcode.com/problems/add-two-numbers/',
      ),

      // Step 7: Recursion & Backtracking
      const DsaProblem(
        id: 's7-1',
        stepNumber: 7,
        stepTitle: 'Step 7: Recursion & Backtracking',
        subTopic: '7.2 Subsequences Pattern',
        title: 'Generate all binary strings, Generate Parentheses',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Pick / Don’t Pick Decision Tree',
        problemUrl: 'https://leetcode.com/problems/generate-parentheses/',
      ),
      const DsaProblem(
        id: 's7-2',
        stepNumber: 7,
        stepTitle: 'Step 7: Recursion & Backtracking',
        subTopic: '7.2 Subsequences Pattern',
        title: 'Combination Sum I & II',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Backtracking with Pruning',
        problemUrl: 'https://leetcode.com/problems/combination-sum/',
      ),
      const DsaProblem(
        id: 's7-3',
        stepNumber: 7,
        stepTitle: 'Step 7: Recursion & Backtracking',
        subTopic: '7.3 Hard Backtracking',
        title: 'N-Queens Problem',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Column and Diagonal Hashing',
        problemUrl: 'https://leetcode.com/problems/n-queens/',
      ),
      const DsaProblem(
        id: 's7-4',
        stepNumber: 7,
        stepTitle: 'Step 7: Recursion & Backtracking',
        subTopic: '7.3 Hard Backtracking',
        title: 'Sudoku Solver',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'State Verification Backtracking',
        problemUrl: 'https://leetcode.com/problems/sudoku-solver/',
      ),

      // Step 9: Stack & Queues
      const DsaProblem(
        id: 's9-1',
        stepNumber: 9,
        stepTitle: 'Step 9: Stack and Queues',
        subTopic: '9.2 Monotonic Stack / Queue',
        title: 'Next Greater Element I & II',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Decreasing Monotonic Stack',
        problemUrl: 'https://leetcode.com/problems/next-greater-element-i/',
      ),
      const DsaProblem(
        id: 's9-2',
        stepNumber: 9,
        stepTitle: 'Step 9: Stack and Queues',
        subTopic: '9.2 Monotonic Stack / Queue',
        title: 'Trapping Rain Water',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Two Pointers / Monotonic Stack',
        problemUrl: 'https://leetcode.com/problems/trapping-rain-water/',
      ),
      const DsaProblem(
        id: 's9-3',
        stepNumber: 9,
        stepTitle: 'Step 9: Stack and Queues',
        subTopic: '9.2 Monotonic Stack / Queue',
        title: 'Largest Rectangle in Histogram',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Previous & Next Smaller Element',
        problemUrl: 'https://leetcode.com/problems/largest-rectangle-in-histogram/',
      ),
      const DsaProblem(
        id: 's9-4',
        stepNumber: 9,
        stepTitle: 'Step 9: Stack and Queues',
        subTopic: '9.3 Advanced Implementation',
        title: 'LRU Cache (Least Recently Used)',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Hash Map + Doubly Linked List',
        problemUrl: 'https://leetcode.com/problems/lru-cache/',
      ),

      // Step 13: Binary Trees
      const DsaProblem(
        id: 's13-1',
        stepNumber: 13,
        stepTitle: 'Step 13: Binary Trees [Traversals, Medium, Hard]',
        subTopic: '13.1 Traversals',
        title: 'Preorder, Inorder, Postorder, Level Order Traversal',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.todo,
        pattern: 'Recursive DFS & Queue BFS',
        problemUrl: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
      ),
      const DsaProblem(
        id: 's13-2',
        stepNumber: 13,
        stepTitle: 'Step 13: Binary Trees [Traversals, Medium, Hard]',
        subTopic: '13.2 Medium Problems',
        title: 'Height and Diameter of Binary Tree',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.todo,
        pattern: 'Post-Order Subtree Depth Rollup',
        problemUrl: 'https://leetcode.com/problems/diameter-of-binary-tree/',
      ),
      const DsaProblem(
        id: 's13-3',
        stepNumber: 13,
        stepTitle: 'Step 13: Binary Trees [Traversals, Medium, Hard]',
        subTopic: '13.2 Medium Problems',
        title: 'Binary Tree Maximum Path Sum',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Bottom-up Max Contribution Path',
        problemUrl: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/',
      ),
      const DsaProblem(
        id: 's13-4',
        stepNumber: 13,
        stepTitle: 'Step 13: Binary Trees [Traversals, Medium, Hard]',
        subTopic: '13.2 Medium Problems',
        title: 'Lowest Common Ancestor (LCA) in Binary Tree',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Divide & Conquer DFS',
        problemUrl: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
      ),
      const DsaProblem(
        id: 's13-5',
        stepNumber: 13,
        stepTitle: 'Step 13: Binary Trees [Traversals, Medium, Hard]',
        subTopic: '13.2 Medium Problems',
        title: 'Vertical Order Traversal / Top View / Bottom View',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Coordinate (Vertical, Level) Mapping',
        problemUrl: 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/',
      ),

      // Step 15: Graphs
      const DsaProblem(
        id: 's15-1',
        stepNumber: 15,
        stepTitle: 'Step 15: Graphs [BFS/DFS, Shortest Path, MST]',
        subTopic: '15.1 Learning & Traversals',
        title: 'Breadth First Search (BFS) and Depth First Search (DFS)',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.todo,
        pattern: 'Adjacency List + Visited Array',
        problemUrl: 'https://takeuforward.org/graph/breadth-first-search-bfs-level-order-traversal/',
      ),
      const DsaProblem(
        id: 's15-2',
        stepNumber: 15,
        stepTitle: 'Step 15: Graphs [BFS/DFS, Shortest Path, MST]',
        subTopic: '15.2 Problems on BFS/DFS',
        title: 'Number of Islands / Rotting Oranges',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Multi-Source BFS / Flood Fill',
        problemUrl: 'https://leetcode.com/problems/rotting-oranges/',
      ),
      const DsaProblem(
        id: 's15-3',
        stepNumber: 15,
        stepTitle: 'Step 15: Graphs [BFS/DFS, Shortest Path, MST]',
        subTopic: '15.3 Topo Sort and DAGs',
        title: 'Course Schedule I & II (Kahn’s Algorithm)',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Indegree Array Topological Sort',
        problemUrl: 'https://leetcode.com/problems/course-schedule-ii/',
      ),
      const DsaProblem(
        id: 's15-4',
        stepNumber: 15,
        stepTitle: 'Step 15: Graphs [BFS/DFS, Shortest Path, MST]',
        subTopic: '15.4 Shortest Path Algorithms',
        title: 'Dijkstra Algorithm (Shortest Path in Weighted Graph)',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Min-Heap Priority Queue Relaxation',
        problemUrl: 'https://takeuforward.org/data-structure/dijkstras-algorithm-using-priority-queue-g-32/',
      ),
      const DsaProblem(
        id: 's15-5',
        stepNumber: 15,
        stepTitle: 'Step 15: Graphs [BFS/DFS, Shortest Path, MST]',
        subTopic: '15.6 Disjoint Set Union (DSU)',
        title: 'Disjoint Set (Union by Rank & Path Compression) / Kruskal MST',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'DSU Find & Union Operations',
        problemUrl: 'https://takeuforward.org/data-structure/disjoint-set-union-by-rank-union-by-size-path-compression-g-46/',
      ),

      // Step 16: Dynamic Programming
      const DsaProblem(
        id: 's16-1',
        stepNumber: 16,
        stepTitle: 'Step 16: Dynamic Programming [1D, 2D, Grids, Strings]',
        subTopic: '16.1 Introduction to DP',
        title: 'Climbing Stairs & Frog Jump (Memoization to Space Optimized)',
        difficulty: DsaDifficulty.easy,
        status: DsaStatus.todo,
        pattern: '1D State Transition',
        problemUrl: 'https://leetcode.com/problems/climbing-stairs/',
      ),
      const DsaProblem(
        id: 's16-2',
        stepNumber: 16,
        stepTitle: 'Step 16: Dynamic Programming [1D, 2D, Grids, Strings]',
        subTopic: '16.2 2D/3D DP and DP on Grids',
        title: 'Grid Unique Paths & Minimum Path Sum',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: '2D Grid Tabulation',
        problemUrl: 'https://leetcode.com/problems/minimum-path-sum/',
      ),
      const DsaProblem(
        id: 's16-3',
        stepNumber: 16,
        stepTitle: 'Step 16: Dynamic Programming [1D, 2D, Grids, Strings]',
        subTopic: '16.3 DP on Subsequences',
        title: 'Subset Sum Equals Target / 0-1 Knapsack Problem',
        difficulty: DsaDifficulty.medium,
        status: DsaStatus.todo,
        pattern: 'Target Sum State Representation',
        problemUrl: 'https://takeuforward.org/data-structure/subset-sum-equal-to-target-dp-14/',
      ),
      const DsaProblem(
        id: 's16-4',
        stepNumber: 16,
        stepTitle: 'Step 16: Dynamic Programming [1D, 2D, Grids, Strings]',
        subTopic: '16.4 DP on Strings',
        title: 'Longest Common Subsequence (LCS) & Edit Distance',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: '2-String Index Matrix Matching',
        problemUrl: 'https://leetcode.com/problems/longest-common-subsequence/',
      ),
      const DsaProblem(
        id: 's16-5',
        stepNumber: 16,
        stepTitle: 'Step 16: Dynamic Programming [1D, 2D, Grids, Strings]',
        subTopic: '16.5 DP on Stocks',
        title: 'Best Time to Buy and Sell Stock with Cooldown / Fee',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'State Machine DP (Hold / Sell / Cooldown)',
        problemUrl: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/',
      ),
      const DsaProblem(
        id: 's16-6',
        stepNumber: 16,
        stepTitle: 'Step 16: Dynamic Programming [1D, 2D, Grids, Strings]',
        subTopic: '16.7 Matrix Chain Multiplication (MCM)',
        title: 'Matrix Chain Multiplication & Burst Balloons',
        difficulty: DsaDifficulty.hard,
        status: DsaStatus.todo,
        pattern: 'Partition DP across [i, j] Range',
        problemUrl: 'https://leetcode.com/problems/burst-balloons/',
      ),
    ];
  }

  static List<String> getStepTitles() {
    return [
      'All Steps',
      'Step 1: Learn the Basics',
      'Step 2: Learn Important Sorting Techniques',
      'Step 3: Solve Problems on Arrays',
      'Step 4: Binary Search [1D, 2D, Search Space]',
      'Step 5: Strings [Basic and Medium]',
      'Step 6: Learn LinkedList [Single, Double, Medium, Hard]',
      'Step 7: Recursion & Backtracking',
      'Step 8: Bit Manipulation',
      'Step 9: Stack and Queues',
      'Step 10: Sliding Window & Two Pointer',
      'Step 11: Heaps / Priority Queue',
      'Step 12: Greedy Algorithms',
      'Step 13: Binary Trees [Traversals, Medium, Hard]',
      'Step 14: Binary Search Trees',
      'Step 15: Graphs [BFS/DFS, Shortest Path, MST]',
      'Step 16: Dynamic Programming [1D, 2D, Grids, Strings]',
      'Step 17: Tries',
      'Step 18: Advanced Strings & Hard Topics',
    ];
  }
}
